### ISSUE TITLE
no resnet module

### ISSUE THREAD

**Issue by GiYeolKim** [Darkbblue/generic-diffusion-feature#2]
Thank you for your hard work.

I'm running the code, and when I pass --show_all_layers as an argument for all versions of Stable Diffusion, the ResNet module doesn't output. What should I do?

**Comment by Darkbblue** [comment]
> Thank you for your hard work.
> 
> I'm running the code, and when I pass --show_all_layers as an argument for all versions of Stable Diffusion, the ResNet module doesn't output. What should I do?

Thanks for your feedback! It turns out that I've missed some feature extraction spots while migrating from an older diffusers version to the current one. I've fixed this issue with the new commit. Please let me know if there's still some problem!

**Comment by GiYeolKim** [comment]
Thank you for your response.

I ran the code you newly committed, but still, the outputs of the res block and vit block aren’t saved, and even with --show_all_layers, only the attention layer is displayed as shown below.

I used config_15_full.json and the sample code you provided.

```
down-level0-repeat0-vit-block0-self-k torch.Size([320, 64, 64])
down-level0-repeat0-vit-block0-self-v torch.Size([320, 64, 64])
down-level0-repeat0-vit-block0-self-map torch.Size([8, 4096, 4096])
down-level0-repeat0-vit-block0-cross-q torch.Size([320, 64, 64])
down-level0-repeat0-vit-block0-cross-map torch.Size([8, 4096, 77])
down-level0-repeat1-vit-block0-self-q torch.Size([320, 64, 64])
down-level0-repeat1-vit-block0-self-k torch.Size([320, 64, 64])
down-level0-repeat1-vit-block0-self-v torch.Size([320, 64, 64])
down-level0-repeat1-vit-block0-self-map torch.Size([8, 4096, 4096])
down-level0-repeat1-vit-block0-cross-q torch.Size([320, 64, 64])
down-level0-repeat1-vit-block0-cross-map torch.Size([8, 4096, 77])
down-level1-repeat0-vit-block0-self-q torch.Size([640, 32, 32])
down-level1-repeat0-vit-block0-self-k torch.Size([640, 32, 32])
down-level1-repeat0-vit-block0-self-v torch.Size([640, 32, 32])
down-level1-repeat0-vit-block0-self-map torch.Size([8, 1024, 1024])
down-level1-repeat0-vit-block0-cross-q torch.Size([640, 32, 32])
down-level1-repeat0-vit-block0-cross-map torch.Size([8, 1024, 77])
down-level1-repeat1-vit-block0-self-q torch.Size([640, 32, 32])
down-level1-repeat1-vit-block0-self-k torch.Size([640, 32, 32])
down-level1-repeat1-vit-block0-self-v torch.Size([640, 32, 32])
down-level1-repeat1-vit-block0-self-map torch.Size([8, 1024, 1024])
down-level1-repeat1-vit-block0-cross-q torch.Size([640, 32, 32])
down-level1-repeat1-vit-block0-cross-map torch.Size([8, 1024, 77])
down-level2-repeat0-vit-block0-self-q torch.Size([1280, 16, 16])
down-level2-repeat0-vit-block0-self-k torch.Size([1280, 16, 16])
down-level2-repeat0-vit-block0-self-v torch.Size([1280, 16, 16])
down-level2-repeat0-vit-block0-self-map torch.Size([8, 256, 256])
down-level2-repeat0-vit-block0-cross-q torch.Size([1280, 16, 16])
down-level2-repeat0-vit-block0-cross-map torch.Size([8, 256, 77])
down-level2-repeat1-vit-block0-self-q torch.Size([1280, 16, 16])
down-level2-repeat1-vit-block0-self-k torch.Size([1280, 16, 16])
down-level2-repeat1-vit-block0-self-v torch.Size([1280, 16, 16])
down-level2-repeat1-vit-block0-self-map torch.Size([8, 256, 256])
down-level2-repeat1-vit-block0-cross-q torch.Size([1280, 16, 16])
down-level2-repeat1-vit-block0-cross-map torch.Size([8, 256, 77])
mid-vit-block0-self-q torch.Size([1280, 8, 8])
mid-vit-block0-self-k torch.Size([1280, 8, 8])
mid-vit-block0-self-v torch.Size([1280, 8, 8])
mid-vit-block0-self-map torch.Size([8, 64, 64])
mid-vit-block0-cross-q torch.Size([1280, 8, 8])
mid-vit-block0-cross-map torch.Size([8, 64, 77])
up-level1-repeat0-vit-block0-self-q torch.Size([1280, 16, 16])
up-level1-repeat0-vit-block0-self-k torch.Size([1280, 16, 16])
up-level1-repeat0-vit-block0-self-v torch.Size([1280, 16, 16])
up-level1-repeat0-vit-block0-self-map torch.Size([8, 256, 256])
up-level1-repeat0-vit-block0-cross-q torch.Size([1280, 16, 16])
up-level1-repeat0-vit-block0-cross-map torch.Size([8, 256, 77])
up-level1-repeat1-vit-block0-self-q torch.Size([1280, 16, 16])
up-level1-repeat1-vit-block0-self-k torch.Size([1280, 16, 16])
up-level1-repeat1-vit-block0-self-v torch.Size([1280, 16, 16])
up-level1-repeat1-vit-block0-self-map torch.Size([8, 256, 256])
up-level1-repeat1-vit-block0-cross-q torch.Size([1280, 16, 16])
up-level1-repeat1-vit-block0-cross-map torch.Size([8, 256, 77])
up-level1-repeat2-vit-block0-self-q torch.Size([1280, 16, 16])
up-level1-repeat2-vit-block0-self-k torch.Size([1280, 16, 16])
up-level1-repeat2-vit-block0-self-v torch.Size([1280, 16, 16])
up-level1-repeat2-vit-block0-self-map torch.Size([8, 256, 256])
up-level1-repeat2-vit-block0-cross-q torch.Size([1280, 16, 16])
up-level1-repeat2-vit-block0-cross-map torch.Size([8, 256, 77])
up-level2-repeat0-vit-block0-self-q torch.Size([640, 32, 32])
up-level2-repeat0-vit-block0-self-k torch.Size([640, 32, 32])
up-level2-repeat0-vit-block0-self-v torch.Size([640, 32, 32])
up-level2-repeat0-vit-block0-self-map torch.Size([8, 1024, 1024])
up-level2-repeat0-vit-block0-cross-q torch.Size([640, 32, 32])
up-level2-repeat0-vit-block0-cross-map torch.Size([8, 1024, 77])
up-level2-repeat1-vit-block0-self-q torch.Size([640, 32, 32])
up-level2-repeat1-vit-block0-self-k torch.Size([640, 32, 32])
up-level2-repeat1-vit-block0-self-v torch.Size([640, 32, 32])
up-level2-repeat1-vit-block0-self-map torch.Size([8, 1024, 1024])
up-level2-repeat1-vit-block0-cross-q torch.Size([640, 32, 32])
up-level2-repeat1-vit-block0-cross-map torch.Size([8, 1024, 77])
up-level2-repeat2-vit-block0-self-q torch.Size([640, 32, 32])
up-level2-repeat2-vit-block0-self-k torch.Size([640, 32, 32])
up-level2-repeat2-vit-block0-self-v torch.Size([640, 32, 32])
up-level2-repeat2-vit-block0-self-map torch.Size([8, 1024, 1024])
up-level2-repeat2-vit-block0-cross-q torch.Size([640, 32, 32])
up-level2-repeat2-vit-block0-cross-map torch.Size([8, 1024, 77])
up-level3-repeat0-vit-block0-self-q torch.Size([320, 64, 64])
up-level3-repeat0-vit-block0-self-k torch.Size([320, 64, 64])
up-level3-repeat0-vit-block0-self-v torch.Size([320, 64, 64])
up-level3-repeat0-vit-block0-self-map torch.Size([8, 4096, 4096])
up-level3-repeat0-vit-block0-cross-q torch.Size([320, 64, 64])
up-level3-repeat0-vit-block0-cross-map torch.Size([8, 4096, 77])
up-level3-repeat1-vit-block0-self-q torch.Size([320, 64, 64])
up-level3-repeat1-vit-block0-self-k torch.Size([320, 64, 64])
up-level3-repeat1-vit-block0-self-v torch.Size([320, 64, 64])
up-level3-repeat1-vit-block0-self-map torch.Size([8, 4096, 4096])
up-level3-repeat1-vit-block0-cross-q torch.Size([320, 64, 64])
up-level3-repeat1-vit-block0-cross-map torch.Size([8, 4096, 77])
up-level3-repeat2-vit-block0-self-q torch.Size([320, 64, 64])
up-level3-repeat2-vit-block0-self-k torch.Size([320, 64, 64])
up-level3-repeat2-vit-block0-self-v torch.Size([320, 64, 64])
up-level3-repeat2-vit-block0-self-map torch.Size([8, 4096, 4096])
up-level3-repeat2-vit-block0-cross-q torch.Size([320, 64, 64])
up-level3-repeat2-vit-block0-cross-map torch.Size([8, 4096, 77])
```

**Comment by Darkbblue** [comment]
> Thank you for your response.
> 
> I ran the code you newly committed, but still, the outputs of the res block and vit block aren’t saved, and even with --show_all_layers, only the attention layer is displayed as shown below.
> 
> I used config_15_full.json and the sample code you provided.
> 
> ```
> down-level0-repeat0-vit-block0-self-k torch.Size([320, 64, 64])
> down-level0-repeat0-vit-block0-self-v torch.Size([320, 64, 64])
> down-level0-repeat0-vit-block0-self-map torch.Size([8, 4096, 4096])
> down-level0-repeat0-vit-block0-cross-q torch.Size([320, 64, 64])
> down-level0-repeat0-vit-block0-cross-map torch.Size([8, 4096, 77])
> down-level0-repeat1-vit-block0-self-q torch.Size([320, 64, 64])
> down-level0-repeat1-vit-block0-self-k torch.Size([320, 64, 64])
> down-level0-repeat1-vit-block0-self-v torch.Size([320, 64, 64])
> down-level0-repeat1-vit-block0-self-map torch.Size([8, 4096, 4096])
> down-level0-repeat1-vit-block0-cross-q torch.Size([320, 64, 64])
> down-level0-repeat1-vit-block0-cross-map torch.Size([8, 4096, 77])
> down-level1-repeat0-vit-block0-self-q torch.Size([640, 32, 32])
> down-level1-repeat0-vit-block0-self-k torch.Size([640, 32, 32])
> down-level1-repeat0-vit-block0-self-v torch.Size([640, 32, 32])
> down-level1-repeat0-vit-block0-self-map torch.Size([8, 1024, 1024])
> down-level1-repeat0-vit-block0-cross-q torch.Size([640, 32, 32])
> down-level1-repeat0-vit-block0-cross-map torch.Size([8, 1024, 77])
> down-level1-repeat1-vit-block0-self-q torch.Size([640, 32, 32])
> down-level1-repeat1-vit-block0-self-k torch.Size([640, 32, 32])
> down-level1-repeat1-vit-block0-self-v torch.Size([640, 32, 32])
> down-level1-repeat1-vit-block0-self-map torch.Size([8, 1024, 1024])
> down-level1-repeat1-vit-block0-cross-q torch.Size([640, 32, 32])
> down-level1-repeat1-vit-block0-cross-map torch.Size([8, 1024, 77])
> down-level2-repeat0-vit-block0-self-q torch.Size([1280, 16, 16])
> down-level2-repeat0-vit-block0-self-k torch.Size([1280, 16, 16])
> down-level2-repeat0-vit-block0-self-v torch.Size([1280, 16, 16])
> down-level2-repeat0-vit-block0-self-map torch.Size([8, 256, 256])
> down-level2-repeat0-vit-block0-cross-q torch.Size([1280, 16, 16])
> down-level2-repeat0-vit-block0-cross-map torch.Size([8, 256, 77])
> down-level2-repeat1-vit-block0-self-q torch.Size([1280, 16, 16])
> down-level2-repeat1-vit-block0-self-k torch.Size([1280, 16, 16])
> down-level2-repeat1-vit-block0-self-v torch.Size([1280, 16, 16])
> down-level2-repeat1-vit-block0-self-map torch.Size([8, 256, 256])
> down-level2-repeat1-vit-block0-cross-q torch.Size([1280, 16, 16])
> down-level2-repeat1-vit-block0-cross-map torch.Size([8, 256, 77])
> mid-vit-block0-self-q torch.Size([1280, 8, 8])
> mid-vit-block0-self-k torch.Size([1280, 8, 8])
> mid-vit-block0-self-v torch.Size([1280, 8, 8])
> mid-vit-block0-self-map torch.Size([8, 64, 64])
> mid-vit-block0-cross-q torch.Size([1280, 8, 8])
> mid-vit-block0-cross-map torch.Size([8, 64, 77])
> up-level1-repeat0-vit-block0-self-q torch.Size([1280, 16, 16])
> up-level1-repeat0-vit-block0-self-k torch.Size([1280, 16, 16])
> up-level1-repeat0-vit-block0-self-v torch.Size([1280, 16, 16])
> up-level1-repeat0-vit-block0-self-map torch.Size([8, 256, 256])
> up-level1-repeat0-vit-block0-cross-q torch.Size([1280, 16, 16])
> up-level1-repeat0-vit-block0-cross-map torch.Size([8, 256, 77])
> up-level1-repeat1-vit-block0-self-q torch.Size([1280, 16, 16])
> up-level1-repeat1-vit-block0-self-k torch.Size([1280, 16, 16])
> up-level1-repeat1-vit-block0-self-v torch.Size([1280, 16, 16])
> up-level1-repeat1-vit-block0-self-map torch.Size([8, 256, 256])
> up-level1-repeat1-vit-block0-cross-q torch.Size([1280, 16, 16])
> up-level1-repeat1-vit-block0-cross-map torch.Size([8, 256, 77])
> up-level1-repeat2-vit-block0-self-q torch.Size([1280, 16, 16])
> up-level1-repeat2-vit-block0-self-k torch.Size([1280, 16, 16])
> up-level1-repeat2-vit-block0-self-v torch.Size([1280, 16, 16])
> up-level1-repeat2-vit-block0-self-map torch.Size([8, 256, 256])
> up-level1-repeat2-vit-block0-cross-q torch.Size([1280, 16, 16])
> up-level1-repeat2-vit-block0-cross-map torch.Size([8, 256, 77])
> up-level2-repeat0-vit-block0-self-q torch.Size([640, 32, 32])
> up-level2-repeat0-vit-block0-self-k torch.Size([640, 32, 32])
> up-level2-repeat0-vit-block0-self-v torch.Size([640, 32, 32])
> up-level2-repeat0-vit-block0-self-map torch.Size([8, 1024, 1024])
> up-level2-repeat0-vit-block0-cross-q torch.Size([640, 32, 32])
> up-level2-repeat0-vit-block0-cross-map torch.Size([8, 1024, 77])
> up-level2-repeat1-vit-block0-self-q torch.Size([640, 32, 32])
> up-level2-repeat1-vit-block0-self-k torch.Size([640, 32, 32])
> up-level2-repeat1-vit-block0-self-v torch.Size([640, 32, 32])
> up-level2-repeat1-vit-block0-self-map torch.Size([8, 1024, 1024])
> up-level2-repeat1-vit-block0-cross-q torch.Size([640, 32, 32])
> up-level2-repeat1-vit-block0-cross-map torch.Size([8, 1024, 77])
> up-level2-repeat2-vit-block0-self-q torch.Size([640, 32, 32])
> up-level2-repeat2-vit-block0-self-k torch.Size([640, 32, 32])
> up-level2-repeat2-vit-block0-self-v torch.Size([640, 32, 32])
> up-level2-repeat2-vit-block0-self-map torch.Size([8, 1024, 1024])
> up-level2-repeat2-vit-block0-cross-q torch.Size([640, 32, 32])
> up-level2-repeat2-vit-block0-cross-map torch.Size([8, 1024, 77])
> up-level3-repeat0-vit-block0-self-q torch.Size([320, 64, 64])
> up-level3-repeat0-vit-block0-self-k torch.Size([320, 64, 64])
> up-level3-repeat0-vit-block0-self-v torch.Size([320, 64, 64])
> up-level3-repeat0-vit-block0-self-map torch.Size([8, 4096, 4096])
> up-level3-repeat0-vit-block0-cross-q torch.Size([320, 64, 64])
> up-level3-repeat0-vit-block0-cross-map torch.Size([8, 4096, 77])
> up-level3-repeat1-vit-block0-self-q torch.Size([320, 64, 64])
> up-level3-repeat1-vit-block0-self-k torch.Size([320, 64, 64])
> up-level3-repeat1-vit-block0-self-v torch.Size([320, 64, 64])
> up-level3-repeat1-vit-block0-self-map torch.Size([8, 4096, 4096])
> up-level3-repeat1-vit-block0-cross-q torch.Size([320, 64, 64])
> up-level3-repeat1-vit-block0-cross-map torch.Size([8, 4096, 77])
> up-level3-repeat2-vit-block0-self-q torch.Size([320, 64, 64])
> up-level3-repeat2-vit-block0-self-k torch.Size([320, 64, 64])
> up-level3-repeat2-vit-block0-self-v torch.Size([320, 64, 64])
> up-level3-repeat2-vit-block0-self-map torch.Size([8, 4096, 4096])
> up-level3-repeat2-vit-block0-cross-q torch.Size([320, 64, 64])
> up-level3-repeat2-vit-block0-cross-map torch.Size([8, 4096, 77])
> ```

Some of the newly committed files are under the /feature/diffusers folder, which should replace the files in your installed diffusers lib according to my installation guide in readme.
It might be because this step is not thoroughly conducted.

**Comment by GiYeolKim** [comment]
Oh, I missed that part. It’s resolved now.
Thank you for your kindness, and I hope only good things come your way in the future!
